language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
jobs:
  include:
  - stage: test
    python: 3.7
    dist: xenial
    sudo: true
  - script: tox -e lint
  - script: pipenv run invoke coverage --publish
    before_script:
    - pip install pipenv
    - pipenv install --dev --skip-lock
  - stage: deploy
    script: skip
    python: 3.6
    deploy:
      provider: pypi
      user: briggySmalls
      distributions: sdist bdist_wheel
      password:
        secure: hJmcbqtm9y68GeShTkvMVd6vKEskzmSUYefwp8jyvQMJgXQ6tGtBGwOThDAxF6QT/MFEG2hITq1HPmHLplzcwXwStjJgHtBY1Nr4fKXqlsyJ+IugfFIuWqciPlzgOQWp07tHQ2HCWXFG5QlRjdZrQ7S9tKxU99S00YSkApMLRBiAmcEfgHWgFmjqDx4FAmFUxn+2eP4lAL49MMFE7IWeobNltFKjRPY4lOLABJE++DkM33cg9JGzKBU8jDYZ/gceZD+fyEWMJmWaqWgwRDUGrOgw2ItsObcYsZd6mgpc4uMccHAnWNA/+JFqgnCTcty7niybi+WUBRw5EaQ0lYNmTeb9T9851f/EsmQlTM3we+eKgmT2XoZ8ytaX0Pqo+/uBjH8TbtxjWZnE3t+8SZS3dT8Bmxofumokg1fwSHUs/jTkuohXl67807663RKlJBA4YmR74bblpqkCGNki13tpqZIHeOl1xLFUsrcV68P1ZRWwkb/ubBIXu+w5tOMY8DyS9957HCSZr2WUpwkYezTTzZFVKTnDbYPJri6M5oPWWHWKcMr+WNFhAzphUaYz3saGin/T1YgjoVZHZwdHtFAvkOSEkZPDNBux2M4GLiJ51EaY6AD14OTY37jwY393TJe1yimL30P1iVPOcSeASVbCYV9RFQS6e+fbEKw7haTFRjE=
      on:
        tags: true
  - script:
    - pipenv run invoke docs
    before_script:
    - pip install pipenv
    - pipenv install --dev --skip-lock
    python: 3.6
    deploy:
      provider: pages
      local-dir: docs/_build
      skip-cleanup: true
      github-token: "$GH_TOKEN"
      keep-history: true
      on:
        branch: master
